# Generated by Django 4.2 on 2023-05-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "season_id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("season_name", models.CharField(max_length=50, null=True)),
                ("season_prem", models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contestants",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("contestant", models.CharField(max_length=50, null=True)),
                ("age", models.IntegerField(default=20, null=True)),
                ("hometown", models.CharField(max_length=100, null=True)),
                ("placement", models.CharField(max_length=100)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.season"
                    ),
                ),
            ],
        ),
    ]
