# Generated by Django 4.2 on 2023-04-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestants",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
